### ISSUE TITLE
Task 2.3: Setup Milestone trên tool quản lý dự án

### ISSUE THREAD

**Issue by nna9220** [nna9220/Nhom-12---Label-Studio#10]
Setup trên FocalBoard - Roadmap

![Image](https://user-images.githubusercontent.com/102048288/226968744-9060b8ac-339f-4bbc-aaca-5c1ee828d9f0.png)

**Comment by ThuyyyTranggg** [comment]
Setup milestone nhỏ trên tool quản lý dự án - Sprint planner:
![image](https://user-images.githubusercontent.com/114237753/227730606-93f148ae-198b-42d1-90f7-0eb4b83a311e.png)

**Comment by nna9220** [comment]
Hoàn thành
