### ISSUE TITLE
Task 2.1: Lên kế hoạch quản lý dự án trong vòng 2 tháng

### ISSUE THREAD

**Issue by nna9220** [nna9220/Nhom-12---Label-Studio#12]
Từ 14/3 - 14/5:
1. Quản lý theo từng Sprint Planner, mỗi sprint là 1 tuần, 1 ngày thực hiện tối thiểu 1 task nhỏ trong task lớn.
2. Tổng hợp 8 Sprint Planner trong 2 tháng sẽ alf một Roadmap. 
3. Đưa các Task vào một Project tasks để theo dõi quá trình thực hiện.
--> Sử dụng tool quản lý dự án - FocalBoard

![Image](https://user-images.githubusercontent.com/102048288/226973977-92d0d873-9a36-4121-89d1-616238370088.png)

Hiện tại : Tuần 2 - Từ 21/3-28/3

**Comment by ThuyyyTranggg** [comment]
Link document: 
https://docs.google.com/document/d/1_Cw7r9B5X__kguSjD1NpzcjsS4zZaEJoh_D7WwykTdk/edit?usp=sharing

**Comment by nna9220** [comment]
Hoàn thành
