### ISSUE TITLE
4.1. Cài đặt Selenium IDE

### ISSUE THREAD

**Issue by nna9220** [nna9220/Nhom-12---Label-Studio#25]

**Comment by nna9220** [comment]
- [ ] Cài đặt trên firefox
- [ ] Tìm hiểu tính năng của Selenium
- [ ] Dùng thử Selenium

**Comment by nna9220** [comment]
1. Cài đặt Selenium trên Firefox
![image](https://user-images.githubusercontent.com/102048288/230157803-6ce08956-8f31-4df5-b726-c85001b14d55.png)

**Comment by ThuyyyTranggg** [comment]
1. Cài đặt Selenium trên Firefox
![image](https://user-images.githubusercontent.com/114237753/230182101-958e80d0-9666-4404-a763-31b53099974e.png)
