### ISSUE TITLE
4.3. Danh sách các giao diện cần xây dựng test và kết quả mong đợi khi test

### ISSUE THREAD

**Issue by nna9220** [nna9220/Nhom-12---Label-Studio#26]

**Comment by nna9220** [comment]
- [ ] Giao diện Đăng ký
- [ ] Giao diện Đăng nhập
- [ ] Giao diện Setting Account
- [ ] Giao diện Tạo dự án mới
- [ ] Giao diện Thêm Data vào dự án
- [ ] Giao diện Setup - Tổng quan về dự án
- [ ] Giao diện Setup - Giao diện dán nhãn
- [ ] Giao diện Setup - Intructions
- [ ] Giao diện Setup - Học máy
- [ ] Giao diện Setup - Lưu trữ trên Cloud
- [ ] Giao diện Setup - Webhook
- [ ] Giao diện Setup - Drop tabs/Delete Project

**Comment by ThuyyyTranggg** [comment]
Link File Quản lý Test, Test case :
https://1drv.ms/x/s!AgBIWZ_Un1pJgRiIwPFe54Blm8O4?e=6LaX06

**Comment by nna9220** [comment]
Tiếp tục update
