### ISSUE TITLE
4.6. Giao diện Đăng nhập

### ISSUE THREAD

**Issue by nna9220** [nna9220/Nhom-12---Label-Studio#30]
Xây dựng Test, Test case cho giao diện Đăng nhập

**Comment by nna9220** [comment]
Link quản lý: https://onedrive.live.com/View.aspx?resid=495A9FD49F594800!152&authkey=!AIjA8V7ngGWbw7g

**Comment by ThuyyyTranggg** [comment]
Thực hiện các test, test case trên giao diện đăng nhập của Label Studio.
Minh chứng các test:
![image](https://user-images.githubusercontent.com/114237753/231084933-29928fb8-dfa1-4e9f-89fe-bc9faf71fba0.png)
