### ISSUE TITLE
4.8. Test - Giao diện Tạo dự án

### ISSUE THREAD

**Issue by nna9220** [nna9220/Nhom-12---Label-Studio#32]
Xây dựng Test, Test Case cho giao diện Tạo dự án

**Comment by nna9220** [comment]
Link quản lý: https://onedrive.live.com/View.aspx?resid=495A9FD49F594800!152&authkey=!AIjA8V7ngGWbw7g

**Comment by ThuyyyTranggg** [comment]
Thực hiện các test, test case trên giao diện đăng nhập của Label Studio.
Minh chứng các test:
![image](https://user-images.githubusercontent.com/114237753/231090404-f4de0f50-ba0b-4840-a8fd-139f008dc9dd.png)
