### ISSUE TITLE
5.2 - 4: Lấy mẫu nhiệm vụ "Sequential sampling"

### ISSUE THREAD

**Issue by ThuyyyTranggg** [nna9220/Nhom-12---Label-Studio#66]
Thực hiện test giao diện Set Up khi lấy mẫu giao diện theo "Sequential sampling"

**Comment by nna9220** [comment]
https://onedrive.live.com/View.aspx?resid=495A9FD49F594800!152&authkey=!AIjA8V7ngGWbw7g
