### ISSUE TITLE
Task 2.2: Setup task trên 1 tool quản lý dự án

### ISSUE THREAD

**Issue by nna9220** [nna9220/Nhom-12---Label-Studio#9]
Setup trên FocalBoard - Sprint Planner

![Image](https://user-images.githubusercontent.com/102048288/226969003-e2ec5365-3635-4f35-97d6-171c76e59e4f.png)

**Comment by ThuyyyTranggg** [comment]
Hoàn thành :)))

**Comment by nna9220** [comment]
Hoàn thành
